spring:
  application:
    name: ToDoList
  datasource:
    url: ${SQLSERVER_URL:jdbc:sqlserver://localhost:1433;databaseName=todo_list;encrypt=true;trustServerCertificate=true}
    username: ${SQLSERVER_USERNAME:sa}
    password: ${SQLSERVER_PASSWORD:YourStrong!Passw0rd}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
  api-docs:
    path: /v3/api-docs
