spring:
  application:
    name: ToDoList
  profiles:
    active: dev
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    open-in-view: false